version: "3.8"
services:
  backend:
    restart: always
    image: 42-node
    build:
      context: ./
      dockerfile: Dockerfile.42-node
    volumes:
      - ./backend/:/app
    ports:
      - 3000:3000
    networks:
      - mynet
    command: sh -c 'npm install && npm run start:dev'

  frontend:
    restart: always
    image: 42-node
    volumes:
      - ./frontend/:/app
    ports:
      - 8080:8080
    networks:
      - mynet
    command: sh -c 'npm install && npm run serve'

networks:
  mynet:
